Repository pylint-dev/pylint-pytest, pull requests merged in 2023-10, with the labels that each got.

#5 Add a release job to publish on pypi on github tag creation
  .github/workflows/release.yml
Labels: enhancement

#4 Add `.pre-commit-config.yaml`
  .git-blame-ignore-revs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/run-tests.yaml
  .pre-commit-config.yaml
  .pylintrc
  README.md
  pylint_pytest/__init__.py
  pylint_pytest/checkers/__init__.py
  pylint_pytest/checkers/class_attr_loader.py
  pylint_pytest/checkers/fixture.py
  pylint_pytest/utils.py
  pyproject.toml
  setup.cfg
  setup.py
  tests/base_tester.py
  tests/input/cannot-enumerate-pytest-fixtures/no_such_package.py
  tests/input/conftest.py
  tests/input/deprecated-positional-argument-for-pytest-fixture/with_args_scope.py
  tests/input/deprecated-positional-argument-for-pytest-fixture/with_kwargs_scope.py
  tests/input/deprecated-positional-argument-for-pytest-fixture/without_scope.py
  tests/input/deprecated-pytest-yield-fixture/func.py
  tests/input/no-member/assign_attr_of_attr.py
  tests/input/no-member/fixture.py
  tests/input/no-member/from_unpack.py
  tests/input/no-member/inheritance.py
  tests/input/no-member/not_using_cls.py
  tests/input/no-member/yield_fixture.py
  tests/input/unused-import/same_name_decorator.py
  tests/input/useless-pytest-mark-decorator/not_pytest_marker.py
  tests/input/useless-pytest-mark-decorator/other_marks_using_for_fixture.py
  tests/test_cannot_enumerate_fixtures.py
  tests/test_no_member.py
  tests/test_pytest_fixture_positional_arguments.py
  tests/test_pytest_mark_for_fixtures.py
  tests/test_pytest_yield_fixture.py
  tests/test_redefined_outer_name.py
  tests/test_regression.py
  tests/test_unused_argument.py
  tests/test_unused_import.py
  tox.ini
Labels: enhancement

#6 Use ruff instead of flake8 pyupgrade autoflake and isort
  .pre-commit-config.yaml
  pylint_pytest/checkers/class_attr_loader.py
  pylint_pytest/checkers/fixture.py
  pylint_pytest/utils.py
  pyproject.toml
  tests/test_cannot_enumerate_fixtures.py
Labels: enhancement

#9 Activate mypy in pre-commit
  .pre-commit-config.yaml
  pylint_pytest/checkers/class_attr_loader.py
  pylint_pytest/checkers/fixture.py
  pylint_pytest/checkers/types.py
  pylint_pytest/utils.py
  pyproject.toml
  tests/base_tester.py
  tests/base_tester_test.py
  tests/test_pytest_yield_fixture.py
Labels: enhancement, CI

#18 Fix testing + coverage
  .codecov.yml
  .github/workflows/run-tests.yaml
  tox.ini
Labels: bug

#19 Improve packaging + Release v1.1.3rc1
  CHANGELOG.md
  MANIFEST.in
  setup.cfg
  setup.py
Labels: release, improvement

#2 fix is pytest fixture
  pylint_pytest/utils.py
  tests/input/redefined-outer-name/direct_import.py
  tests/test_redefined_outer_name.py
Labels: bug
